import type { IconType } from "react-icons"
import {
  SiAntdesign,
  SiAuth0,
  SiClerk,
  SiCloudinary,
  SiCss,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiFramer,
  SiGraphql,
  SiHeroui,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPassport,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiShadcnui,
  SiSocketdotio,
  SiTailwindcss,
  SiTanstack,
  SiTypescript,
} from "react-icons/si"

/** Maps a resume skill/stack label to its brand glyph. Labels with no reliable brand mark (SQL, React Native, Photoshop) are intentionally absent — callers fall back to a text-only chip. */
export const TECH_ICONS: Record<string, IconType> = {
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Python: SiPython,
  HTML: SiHtml5,
  CSS: SiCss,
  "React.js": SiReact,
  React: SiReact,
  "Next.js": SiNextdotjs,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  FastAPI: SiFastapi,
  Prisma: SiPrisma,
  "Tailwind CSS": SiTailwindcss,
  "Ant Design": SiAntdesign,
  "Shadcn UI": SiShadcnui,
  HeroUI: SiHeroui,
  "Framer Motion": SiFramer,
  "Redux Toolkit": SiRedux,
  "TanStack Query": SiTanstack,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  GraphQL: SiGraphql,
  "Socket.IO": SiSocketdotio,
  Clerk: SiClerk,
  Auth0: SiAuth0,
  "Passport.js": SiPassport,
  Firebase: SiFirebase,
  Cloudinary: SiCloudinary,
  Figma: SiFigma,
}
